version: '2'
services:
  web:
    # build: ./node-app
    ports:
    - "8080:8080"
    image: shengwu0713/web:${IMAGE_TAG:-latest}
    volumes:
      - shared-volume:/src
  cron:
    # build: ./cron-app
    image: shengwu0713/cron:${IMAGE_TAG:-latest}
    volumes:
      - shared-volume:/src
volumes:
  shared-volume:

